[custom.all.epoll]
type   = "local"
path   = "."
ipkg   = "epoll.ipkg"
test   = "test/test.ipkg"

[custom.all.epoll-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.array]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"
